# See https://docs.edukates.io/en/latest/runtime-environment/workshop-definition.html
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: oam-office-hours
spec:
  title: OAM - Configure a Cloud Native App on a Modern Orchestrated Platform
  description: OAM - Configure a Cloud Native App on a Modern Orchestrated Platform
  vendor: eduk8s.io
  difficulty: beginner
  duration: 120m
  url: https://github.com/platform-acceleration-lab/oam-office-hours
  content:
    # Use the default image, one of the pre-existing ones, or you can build your own
    # https://docs.edukates.io/en/develop/runtime-environment/workshop-definition.html#container-image-for-the-workshop
    image: jdk11-environment:*
    files: http://files.$(workshop_namespace).svc.cluster.local/workshop.tar.gz
  session:
    env:
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    #- name: AUTH_USERNAME
    #  value: "teste"
    #- name: AUTH_PASSWORD
    #  value: "teste"
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    dashboards:
    - name: Lecture
      url: https://vimeo.com/showcase/8381366/embed
  environment:
    objects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: instructions
              image: localhost:5000/oam-office-hours
              # NOTE: always make sure your workshop YAML ends with the files deployment