apiVersion: training.eduk8s.io/v1alpha1
kind: WorkshopEnvironment
metadata:
  name: lab-markdown-sample
spec:
  workshop:
    name: lab-markdown-sample
  request:
    enabled: true
  session:
    ingress:
      domain: magic-127-0-0-1.nip.io
      protocol: https